# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: wordpress
#   name: wordpress
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 80
#     nodePort: 32323
#   selector:
#     app: wordpress
#   type: NodePort
# status:
#   loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32323
  selector:
    app: wordpress
  type: NodePort
status:
  loadBalancer: {}
