# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wordpress-pvc
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-wpws
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
