# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:5.7
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               value: redhat
#             - name: MYSQL_DATABASE
#               value: wpdb
#             - name: MYSQL_USER
#               value: shai
#             - name: MYSQL_PASSWORD
#               value: redhat
#           ports:
#             - containerPort: 3306
#           volumeMounts:
#             - name: mysql-storage
#               mountPath: /var/lib/mysql
#       volumes:
#         - name: mysql-storage
#           persistentVolumeClaim:
#             claimName: mysql-pvc-dbws
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: redhat
            - name: MYSQL_DATABASE
              value: wpdb
            - name: MYSQL_USER
              value: shai
            - name: MYSQL_PASSWORD
              value: redhat
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc-dbws
